"""Adicionando preco_total_venda a tabela de vendas

Revision ID: 0f2d71f30463
Revises: 0690314460b5
Create Date: 2025-03-26 21:58:02.417086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2d71f30463'
down_revision = '0690314460b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_total_venda', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('preco_total_venda')

    # ### end Alembic commands ###
