"""Adiciona coluna quantidade ao modelo Produto

Revision ID: 353249ebaf55
Revises: f1fe05526d6b
Create Date: 2025-04-05 17:54:21.203596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353249ebaf55'
down_revision = 'f1fe05526d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_produto_id'], ['tipo_produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('produto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tipo_produto_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_produto_id'], ['tipo_produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('produtos')
    # ### end Alembic commands ###
